-- Demo-customer DDL for the postgres connector conformance tests.
-- Exercises every mapped catalog fact: comments, defaults, identity and
-- generated columns, enum-typed columns, PK/FK/unique constraints,
-- non-constraint indexes (plain, partial, unique-without-constraint),
-- a partitioned parent with runtime-artifact children, a cross-schema
-- view, and an indexed materialized view.

CREATE SCHEMA reporting;

CREATE TYPE public.order_status AS ENUM ('pending', 'paid', 'cancelled', 'refunded');

CREATE TABLE public.users (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    email text NOT NULL CONSTRAINT users_email_key UNIQUE,
    full_name text,
    created_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.users IS 'Registered accounts. Rows are soft-deleted via deleted_at.';
COMMENT ON COLUMN public.users.email IS 'Lowercased at the application layer; citext migration pending.';

CREATE TABLE public.orders (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.users (id),
    status public.order_status NOT NULL DEFAULT 'pending',
    total_cents integer NOT NULL CHECK (total_cents >= 0),
    total_dollars numeric(12,2) GENERATED ALWAYS AS (total_cents / 100.0) STORED,
    created_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON COLUMN public.orders.status IS 'pending | paid | cancelled | refunded';
CREATE INDEX orders_created_at_idx ON public.orders (created_at);
CREATE UNIQUE INDEX orders_one_pending_per_user ON public.orders (user_id) WHERE status = 'pending';

CREATE TABLE public.order_items (
    order_id bigint NOT NULL REFERENCES public.orders (id),
    product_sku text NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    UNIQUE (order_id, product_sku)
);

-- Partitioned parent: the logical estate. Children are the runtime
-- artifacts the snapshot must exclude (DECISIONS.md D-17).
CREATE TABLE public.events (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    occurred_at timestamptz NOT NULL,
    payload text
) PARTITION BY RANGE (occurred_at);
CREATE TABLE public.events_2026_06 PARTITION OF public.events
    FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE public.events_2026_07 PARTITION OF public.events
    FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');

CREATE VIEW reporting.v_daily_revenue AS
SELECT date_trunc('day', o.created_at) AS day,
       sum(o.total_cents) AS revenue_cents,
       count(*) AS order_count
FROM public.orders o
WHERE o.status = 'paid'
GROUP BY 1;
COMMENT ON VIEW reporting.v_daily_revenue IS 'Paid revenue per calendar day.';

CREATE MATERIALIZED VIEW public.mv_user_ltv AS
SELECT o.user_id, sum(o.total_cents) AS ltv_cents
FROM public.orders o
WHERE o.status = 'paid'
GROUP BY o.user_id;
CREATE UNIQUE INDEX mv_user_ltv_user_idx ON public.mv_user_ltv (user_id);
